Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 40

Metrics/ParameterLists:
  Max: 7

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'LICENSE.txt'
    - 'README.md'
    - 'Rakefile'
    - 'bin/*'
    - 'bitex_bot.gemspec'
    - 'settings.rb.sample'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'lib/capistrano/**/*'
    - 'lib/bitex_bot/database.rb'
    - 'lib/bitex_bot/version.rb'
    - 'shared/**/*'
