Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/AbcSize:
  Max: 16

Metrics/ClassLength:
  Max: 130

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 7

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'LICENSE.txt'
    - 'README.md'
    - 'Rakefile'
    - 'bin/*'
    - 'bitex_bot.gemspec'
    - 'settings.rb.sample'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'lib/bitex_bot/database.rb'
